#!/usr/bin/env python3
"""Emit the name-constraint fixtures and assertions for iPXE's x509 self-test.

Reads the DER produced by gen-nc-certs.sh and writes two C fragments that
gen-patch.sh splices into src/tests/x509_test.c.
"""
import hashlib, pathlib, sys, textwrap

OUT = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else "out")

def bytes_block(data, indent, macro):
    body = ", ".join(f"0x{b:02x}" for b in data)
    lines = textwrap.wrap(body, width=62)
    pad = "\t" * indent + "       "
    first = f"\t{macro} ( {lines[0]}"
    rest = "".join("\n" + pad + l for l in lines[1:])
    return first + rest + " )"

DESCRIPTIONS = {
    "nc_root":       "Unconstrained self-signed root",
    "nc_ca":         "CA permitting DNS:example.com and IP:10.0.0.0/8",
    "nc_excl_ca":    "CA permitting DNS:example.com, excluding DNS:bad.example.com",
    "nc_unsup_ca":   "CA with an rfc822Name constraint that cannot be enforced",
    "nc_subca":      "Unconstrained sub-CA beneath nc_ca",
    "nc_leaf":       "DNS:host.example.com -- within the permitted subtree",
    "nc_leaf_exact": "DNS:example.com -- equal to the permitted subtree",
    "nc_leaf_bad":   "DNS:notexample.com -- shares a suffix but not a label boundary",
    "nc_leaf_ip":    "IP:10.1.2.3 -- within the permitted network",
    "nc_leaf_ip_bad":"IP:192.168.1.1 -- outside the permitted network",
    "nc_leaf_ip6":   "IPv6 address against an IPv4-only permitted subtree",
    "nc_leaf_mail":  "rfc822Name only -- a type no subtree constrains",
    "nc_leaf_cn":    "No subjectAltName; commonName within the permitted subtree",
    "nc_leaf_cn_bad":"No subjectAltName; commonName outside the permitted subtree",
    "nc_deep":       "Two levels below the constrained CA, within the subtree",
    "nc_deep_bad":   "Two levels below the constrained CA, outside the subtree",
    "nc_leaf_excl":  "Matches the permitted subtree but also the excluded one",
}

ORDER = ["nc_root", "nc_ca", "nc_excl_ca", "nc_unsup_ca", "nc_subca",
         "nc_leaf", "nc_leaf_exact", "nc_leaf_bad", "nc_leaf_ip",
         "nc_leaf_ip_bad", "nc_leaf_ip6", "nc_leaf_mail", "nc_leaf_cn",
         "nc_leaf_cn_bad", "nc_deep", "nc_deep_bad", "nc_leaf_excl"]

defs = ["""/*
 * Name constraint test certificates.
 *
 * Generated by contrib/name-constraints/gen-nc-certs.sh, which documents the
 * hierarchy and what each certificate is for.  Every fixture is also checked
 * with "openssl verify", so that these expectations are not merely this
 * implementation agreeing with itself.
 */
"""]
for name in ORDER:
    der = (OUT / f"{name}.der").read_bytes()
    fp = hashlib.sha256(der).digest()
    defs.append(f"/* {DESCRIPTIONS[name]} */\nCERTIFICATE ( {name}_crt,\n"
                f"{bytes_block(der, 1, 'DATA')},\n"
                f"{bytes_block(fp, 1, 'FINGERPRINT')} );\n")

defs.append("""/** Certificate store trusting the name constraint test root */
static struct x509_root nc_root = {
\t.refcnt = REF_INIT ( ref_no_free ),
\t.digest = &x509_test_algorithm,
\t.count = 1,
\t.fingerprints = nc_root_crt_fingerprint,
};

/** Time at which all name constraint test certificates are valid */
static time_t nctest_time = 1775000000ULL; /* Sat Mar 28 20:53:20 2026 */
""")

CHAINS = [
    ("nc_chain",         ["nc_leaf_crt", "nc_ca_crt", "nc_root_crt"]),
    ("nc_exact_chain",   ["nc_leaf_exact_crt", "nc_ca_crt", "nc_root_crt"]),
    ("nc_bad_chain",     ["nc_leaf_bad_crt", "nc_ca_crt", "nc_root_crt"]),
    ("nc_ip_chain",      ["nc_leaf_ip_crt", "nc_ca_crt", "nc_root_crt"]),
    ("nc_ip_bad_chain",  ["nc_leaf_ip_bad_crt", "nc_ca_crt", "nc_root_crt"]),
    ("nc_ip6_chain",     ["nc_leaf_ip6_crt", "nc_ca_crt", "nc_root_crt"]),
    ("nc_mail_chain",    ["nc_leaf_mail_crt", "nc_ca_crt", "nc_root_crt"]),
    ("nc_cn_chain",      ["nc_leaf_cn_crt", "nc_ca_crt", "nc_root_crt"]),
    ("nc_cn_bad_chain",  ["nc_leaf_cn_bad_crt", "nc_ca_crt", "nc_root_crt"]),
    ("nc_deep_chain",    ["nc_deep_crt", "nc_subca_crt", "nc_ca_crt", "nc_root_crt"]),
    ("nc_deep_bad_chain",["nc_deep_bad_crt", "nc_subca_crt", "nc_ca_crt", "nc_root_crt"]),
    ("nc_excl_chain",    ["nc_leaf_excl_crt", "nc_excl_ca_crt", "nc_root_crt"]),
]
for cname, certs in CHAINS:
    args = ", ".join("&" + c for c in certs)
    defs.append(f"CHAIN ( {cname}, {args} );\n")

pathlib.Path("nc_defs.c.inc").write_text("\n".join(defs))

PASS = ["nc_chain", "nc_exact_chain", "nc_ip_chain", "nc_mail_chain",
        "nc_cn_chain", "nc_deep_chain"]
FAIL = ["nc_bad_chain", "nc_ip_bad_chain", "nc_ip6_chain", "nc_cn_bad_chain",
        "nc_deep_bad_chain", "nc_excl_chain"]

parse = "\n".join(f"\tx509_certificate_ok ( &{n}_crt );" for n in ORDER
                  if n != "nc_unsup_ca")
chains = "\n".join(f"\tx509_chain_ok ( &{c} );" for c, _ in CHAINS)
ok = "\n".join(f"\tx509_validate_chain_ok ( &{c}, nctest_time,\n"
               f"\t\t\t\t &empty_store, &nc_root );" for c in PASS)
bad = "\n".join(f"\tx509_validate_chain_fail_ok ( &{c}, nctest_time,\n"
                f"\t\t\t\t      &empty_store, &nc_root );" for c in FAIL)
puts = "\n".join(f"\tx509_put ( {n}_crt.cert );" for n in reversed(ORDER)
                 if n != "nc_unsup_ca")

pathlib.Path("nc_exec.c.inc").write_text(f"""	/* Parse name constraint certificates.  The CA carrying a constraint
	 * that cannot be enforced must be refused outright: a critical
	 * extension we do not understand may not simply be ignored.
	 */
{parse}
	x509_certificate_fail_ok ( &nc_unsup_ca_crt );

	/* Parse name constraint chains */
{chains}

	/* Names within the permitted subtrees */
{ok}

	/* Names outside the permitted subtrees, or inside an excluded one.
	 * nc_deep_bad_chain is the case that matters most: the constraint it
	 * violates lives two levels up, so an implementation checking only a
	 * certificate's immediate issuer would wrongly accept it.
	 */
{bad}

""")
pathlib.Path("nc_puts.c.inc").write_text(puts + "\n")
print("wrote nc_defs.c.inc, nc_exec.c.inc, nc_puts.c.inc")
