#!/bin/bash
#
# Guard against silent iPXE option drift.
#
#   ./tools/check-linked-objects.sh            -> compare against the baselines
#   ./tools/check-linked-objects.sh --update    -> rewrite the baselines
#
# Run it after buildipxe.sh; it reads that build's output, so it needs no
# knowledge of how the build works.
#
# WHY THIS EXISTS
#
# fogproject f61a90d97 (2026-01-26) copied upstream iPXE's config headers in
# wholesale. Upstream gates several options behind "not historically included
# in BIOS builds" blocks -- historically for upstream, not for FOG -- so that
# one commit silently turned off ten options FOG had shipped for years. They
# came to light one at a time, each after somebody hit the symptom:
#
#   CONSOLE_PCBIOS        blank screen on real BIOS hardware        (GH-958)
#   ACPI_SETTINGS         missing ${acpi/...} settings              (GH-958)
#   DOWNLOAD_PROTO_FILE   no file:// on EFI                         (GH-958)
#   PARAM_CMD             every legacy-BIOS boot fails outright     (#3)
#   CONSOLE_CMD           no boot-menu background, sanboot fallthrough (#3)
#   CERT/DIGEST/NTP/PCI/USB/VLAN_CMD  diagnostics FOG's docs use    (#3)
#   CONSOLE_FRAMEBUFFER   boot menu renders as unstyled text on BIOS
#   DOWNLOAD_PROTO_HTTPS  every BIOS client on an HTTPS server dies
#   DOWNLOAD_PROTO_FTP/NFS, NET_PROTO_LLDP, PXE_CMD  silent feature loss
#
# Six releases to chase down one commit, because each fix only addressed the
# option whose symptom had been reported. This check turns that into a standing
# property of the repository: any change to the effective feature set of a
# shipped binary fails CI and has to be acknowledged in the same pull request.
#
# WHY THE LINKED OBJECT LIST, RATHER THAN THE HEADERS
#
# Reading #defines out of the headers is what everyone did by eye, and it misses
# things twice over. An option can be lost through a #define becoming a comment,
# or through an #undef in a platform block hundreds of lines away, so a textual
# diff of the header does not tell you what the binary ends up with. Worse,
# GH-958 was the reverse case: the #define was absent, so config_pcbios.c's
# REQUIRE_OBJECT never fired and NO console driver linked -- a header audit that
# only compared option state would have called that file correct.
#
# The linker's map file is the ground truth. It lists exactly which objects were
# pulled into the image, so vesafb.o, https.o and bios_console.o are present or
# they are not, and no amount of preprocessor indirection can hide it. It also
# costs nothing to keep honest: it is generated by the real build rather than by
# a harness here that reimplements the build's include paths and would rot.
#
# WHEN THIS FAILS
#
# A diff is not automatically a bug -- bumping IPXEVER legitimately changes the
# object set, and so does deliberately enabling an option. The check exists to
# make sure a human sees the change. Read the diff; if it is intended, rerun
# with --update and commit the new baseline alongside the change that caused it.
set -euo pipefail

# The baseline is a sorted list compared with diff, so the sort has to mean the
# same thing everywhere. Glibc's default collation ignores punctuation at the
# first pass, so en_US.UTF-8 orders "ipstat_cmd.o" and "ipstat.o" one way and
# C orders them the other. Without this the check fails on a developer box or a
# CI runner purely because its locale differs, reporting every object as both
# removed and added -- which is exactly what the first CI run of this script
# did. LC_ALL=C makes the byte order the contract.
export LC_ALL=C

FOGDIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
BASE="${FOGDIR}/build"
BASELINEDIR="${FOGDIR}/tools/linked-objects"

# name:mapfile. One representative binary per build tree, because every target
# within a tree is linked from the same blib.a against the same config headers
# -- undionly.kkpxe and ipxe.lkrn cannot disagree about whether vesafb.o is in.
# The three trees genuinely can disagree: BIOS and EFI are separate clones with
# separate headers (src/config vs src-efi/config), and arm64 is a separate
# compile of the EFI tree whose object set differs by architecture.
#
# The EFI targets are built once, EMBED-less -- see the long note in
# buildipxe.sh. The BIOS targets are still built twice (EMBED=ipxescript, then
# ipxescript10sec) so undionly.kkpxe's map is from that second pass. That is
# fine and stable: EMBED changes which script bytes land in embedded.o, not
# which objects the linker pulls in, and config.o references obj_embedded
# either way -- which is also why dropping EMBED from the EFI builds did not
# move these baselines.
TARGETS=(
    "undionly.kkpxe:${BASE}/ipxe/src/bin/undionly.kkpxe.tmp.map"
    "x86_64-efi-snponly.efi:${BASE}/ipxe-efi/src/bin-x86_64-efi/snponly.efi.tmp.map"
    "arm64-efi-snponly.efi:${BASE}/ipxe-efi/src/bin-arm64-efi/snponly.efi.tmp.map"
)

# Pull the archive members the linker actually used. Everything iPXE compiles
# lands in blib.a and the linker takes only what is referenced, so this is the
# feature set of the image. Sorted and de-duplicated: a map file lists an object
# once per symbol that dragged it in, and the ordering is link order, which is
# noise for our purposes.
extract() {
    grep -oE "blib\.a\([a-z0-9_]+\.o\)" "$1" \
        | sed 's/^blib\.a(\(.*\))$/\1/' \
        | sort -u
}

mode="${1:-check}"
[[ $mode == "--update" ]] && mode="update"

mkdir -p "$BASELINEDIR"
missing=0
failed=0

for entry in "${TARGETS[@]}"; do
    name="${entry%%:*}"
    map="${entry#*:}"
    baseline="${BASELINEDIR}/${name}.txt"

    if [[ ! -r $map ]]; then
        echo "MISSING  $name -- no map at $map"
        echo "         run ./buildipxe.sh first"
        missing=1
        continue
    fi

    current=$(mktemp)
    extract "$map" > "$current"

    if [[ $mode == "update" ]]; then
        cp "$current" "$baseline"
        echo "UPDATED  $name ($(wc -l < "$baseline") objects)"
        rm -f "$current"
        continue
    fi

    if [[ ! -r $baseline ]]; then
        echo "MISSING  $name -- no baseline at $baseline"
        echo "         create it with: $0 --update"
        missing=1
        rm -f "$current"
        continue
    fi

    if diff -q "$baseline" "$current" >/dev/null; then
        echo "OK       $name ($(wc -l < "$baseline") objects)"
    else
        echo "CHANGED  $name"
        # -/+ rather than a unified diff: the interesting information is only
        # ever which objects came and went, and a hunk header helps nobody.
        diff "$baseline" "$current" | grep -E "^[<>]" \
            | sed 's/^</  - removed: /; s/^>/  + added:   /'
        failed=1
    fi
    rm -f "$current"
done

if [[ $missing -eq 1 ]]; then
    exit 2
fi

if [[ $failed -eq 1 ]]; then
    cat <<'MSG'

The feature set of at least one shipped binary changed.

If that was the point of your change -- you enabled an option, or bumped
IPXEVER -- rerun with --update and commit the new baseline in this same pull
request, so the diff is reviewed rather than discovered later by a user whose
clients stopped booting.

If it was not the point of your change, you have found drift. See the note at
the top of this script for what that has cost before.
MSG
    exit 1
fi

echo "All binaries match their baselines."
